### ISSUE TITLE
No visual effect of the darkness consuming the player

### ISSUE THREAD

**Issue by D-Bigboy-302** [dcaedll/OminousDarkness#1]
Forge:1.18.2 - 40.1.20
Mod Version: 1.1.1

I'm not getting the visual effect when the darkness consumes the player. I thought it was a mod conflict, but even when I only load ominous darkness it doesn't appear. Only begins damaging the player.

**Comment by dcaedll** [comment]
Are you using Optifine? Can you post some logs?

**Comment by D-Bigboy-302** [comment]
I was using optifine, but even when I loaded ominous darkness by itself, no mods or resource packs, still nothing. Here's a log:

[latest.log](https://github.com/dcaedll/OminousDarkness/files/8747131/latest.log)

**Comment by D-Bigboy-302** [comment]
It was a config issue. I apologize for taking up your time
