### ISSUE TITLE
[1.16.5] Server-side incompatibility

### ISSUE THREAD

**Issue by OcrSu** [dcaedll/OminousDarkness#4]
[crash-2022-07-29_21.49.25-fml.txt](https://github.com/dcaedll/OminousDarkness/files/9220742/crash-2022-07-29_21.49.25-fml.txt)
Java11

**Comment by dcaedll** [comment]
Also happens to be the case for other game versions.

**Comment by dcaedll** [comment]
Fixed in 1.16-1.2.1, 1.17-1.2.1, 1.18-1.2.1, 1.19-1.1.1
