### ISSUE TITLE
Crash on Startup w/ Config Changes

### ISSUE THREAD

**Issue by Roonas** [dcaedll/OminousDarkness#6]
Game Version: 1.19.2
Forge Version: 43.2.6
Mod Version: Latest- 1.19.1.1.1

Modifying the config for potion effects applied to the player results in a crash on startup. Example of formatting:`["minecraft:blindness"[timing=75%]]` or `["minecraft:darkness"[timing=75%], ["minecraft:blindness"[timing=90%]]`

[crash-2023-03-09_12.42.09-client.txt](https://github.com/dcaedll/OminousDarkness/files/10936276/crash-2023-03-09_12.42.09-client.txt)

**Comment by dcaedll** [comment]
Quotation marks are there for list elements, not for effect names. The syntax is as follows: "effect_name1[...][...][...]", "effect_name2[...][...][...]", etc.
